repos:
  - repo: https://github.com/python-poetry/poetry
    rev: 1.4.0
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: [ "-f", "requirements.txt", "-o", "requirements.txt" ]

  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        # 85 since interrogate isn't ignoring __init__.py as configured
        # fails without --quiet
        args: [ "--fail-under", "85", "-v"]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [ "--profile", "black", "--filter-files" ]
        name: Sort imports isort (python)
      - id: isort
        args: [ "--profile", "black", "--filter-files" ]
        name: Sort imports isort (cython)
        types: [ cython ]
      - id: isort
        args: [ "--profile", "black", "--filter-files" ]
        name: Sort imports isort (pyi)
        types: [ pyi ]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        name: black check (Python)

  #  - repo: local
  #    hooks:
  #      - id: pylint
  #        name: pylint
  #        entry: pylint
  #        language: system
  #        types: [ python ]
  #        args:
  #          [
  #            "-rn", # Only display messages
  #            "-sn", # Don't display the score
  #            "--rcfile=pylintrc", # Link to your config file
  #          ]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.256'
    hooks:
      - id: ruff

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [ "-c", "pyproject.toml" ]