repos:
  - repo: https://github.com/python-poetry/poetry
    rev: 1.4.0
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: [ "-f", "requirements.txt", "-o", "requirements.txt" ]

  # automatically upgrades to new python syntax (might not be wanted when support multiple python versions)
  #  - repo: https://github.com/asottile/pyupgrade
  #    rev: v3.3.1
  #    hooks:
  #      - id: pyupgrade

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [ "--profile", "black", "--filter-files" ]
        name: Sort imports isort (python)
      - id: isort
        args: [ "--profile", "black", "--filter-files" ]
        name: Sort imports isort (cython)
        types: [ cython ]
      - id: isort
        args: [ "--profile", "black", "--filter-files" ]
        name: Sort imports isort (pyi)
        types: [ pyi ]

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        name: black check (Python)

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
      - id: mypy
        args: [ --config-file=./pyproject.toml ]

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.299
    hooks:
      - id: pyright

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.5.1
    hooks:
      - id: docformatter
        args: [ "--config", "./pyproject.toml", "-c" ]

  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        # 85 since interrogate isn't ignoring __init__.py as configured
        # fails without --quiet
        # TODO set "0" to 85: currently broken when using pre-commit in hook. Badge shows correct value
        args: [ "--fail-under", "0", "--quiet", "-c", "./pyproject.toml", "." ]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.256'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [ "-c", "./pyproject.toml" ]